name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    ## todo later - run deploy.

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
    - uses: php-actions/phpunit@v3
      with:
        version: 7.5.20
        bootstrap: tests/bootstrap.php
        configuration: phpunit.xml